#!/bin/bash

echo "🔍 Wallet Detection Check"
echo "========================="
echo ""
echo "This will help identify wallet connection issues."
echo ""

# Check if common wallet extensions are mentioned in the logs
echo "Common wallet extensions to install:"
echo ""
echo "1. MetaMask (Most Popular)"
echo "   Download: https://metamask.io/download/"
echo "   • Chrome/Brave: Visit Chrome Web Store"
echo "   • Firefox: Visit Firefox Add-ons"
echo "   • After install: Refresh Wadah app"
echo ""
echo "2. Coinbase Wallet"
echo "   Download: https://www.coinbase.com/wallet"
echo "   • Chrome extension available"
echo "   • Creates a smart wallet automatically"
echo ""
echo "3. Rainbow Wallet"
echo "   Download: https://rainbow.me/extension"
echo ""
echo "========================="
echo ""
echo "Quick Check:"
echo ""
echo "1. Do you have ANY crypto wallet browser extension installed?"
echo "   • Check your browser extensions"
echo "   • Look for MetaMask, Coinbase Wallet, etc."
echo ""
echo "2. If NO wallet installed:"
echo "   → Install MetaMask (easiest): https://metamask.io"
echo "   → Create a wallet (takes 2 minutes)"
echo "   → Then try 'Injected' again"
echo ""
echo "3. If YES wallet is installed but not working:"
echo "   → Make sure the wallet extension is ENABLED"
echo "   → Make sure the wallet is UNLOCKED"
echo "   → Try refreshing Wadah Desktop"
echo ""
echo "========================="
echo ""
echo "Alternative: Use Coinbase Option"
echo ""
echo "If you don't want to install anything:"
echo "  • Click 'Coinbase' instead of 'Injected'"
echo "  • It will create a Smart Wallet for you"
echo "  • No extension needed!"
echo ""

